### ISSUE TITLE
Do we want any open text response questions?

### ISSUE THREAD

**Issue by JamesPHoughton** [willschulz/bad-influence#21]
For example, @xehu [notes](https://github.com/willschulz/bad-influence/issues/2#issuecomment-1453951679)
> In the post-survey, the last question seems best suited for an open-text: that is, the "are there any situations in which you would approve of a police officer striking an adult male citizen" seems to be more interesting if we ask participants to both answer yes or no, and provide an explanation of which situations, if yes, they imagine to be acceptable.

**Comment by willschulz** [comment]
I agree that this question's binary response is imprecise, but I think we want to retain the response format to facilitate comparison to GSS responses.
