### ISSUE TITLE
Go from likert scales to sliders with scale points?

### ISSUE THREAD

**Issue by JamesPHoughton** [willschulz/bad-influence#23]
Currently, we do everything with likert scales. Any reason we should change this? If so we'll need to build up sliders (https://github.com/Watts-Lab/deliberation-empirica/issues/424)

**Comment by xehu** [comment]
I tend to be against general sliders, based on personal experience...

- People have very different ideas of what one 'notch' on a slider means, leading to more noise;
- Anchoring effects on sliders are super strong. If you anchor it in the middle, people submit very low-variance responses around the anchor, and if you give no anchor at all, people tend to get confused about how to click the slider.

**Comment by willschulz** [comment]
I'm fine with dropping slides from the agenda.
