### ISSUE TITLE
✈️ pilot 5/3

### ISSUE THREAD

**Issue by RachelAbigail** [willschulz/bad-influence#8]
- [ ] add time to identify the leader section
- [ ] implement attention check/notification if a participant is taking too long to complete the pre-survey
- [ ] implement a topic model to check whether discussion follows the actual discussion prompts
- [ ] strike question interpreted as “hit” in opposition to “shoot” - consider rewording?
- [ ] potentially cut time from post-discussion survey - seemed a bit too long
- [ ] have at least 1 research team member participate in each of the next few sessions with real participants

**Comment by JamesPHoughton** [comment]
Issues moved to https://github.com/users/willschulz/projects/1/views/1, closing here.
